### PR TITLE
Fix package name printing

### LINKED ISSUE #516: Package names are printed wrong when DI or ADTypes is only `import`ed
```julia
julia> import DifferentiationInterface

julia> DifferentiationInterface.package_name(DifferentiationInterface.AutoForwardDiff())
"pes.AutoForwardDiff"

julia> using DifferentiationInterface

julia> DifferentiationInterface.package_name(DifferentiationInterface.AutoForwardDiff())
"ForwardDiff"
```

### PR DESCRIPTION
**Pull request by gdalle**
**DI source**

- Fix package name parsing from `ADTypes` backend string

```julia
julia> import DifferentiationInterface

julia> DifferentiationInterface.package_name(DifferentiationInterface.AutoForwardDiff())
"ForwardDiff"

julia> using DifferentiationInterface

julia> DifferentiationInterface.package_name(DifferentiationInterface.AutoForwardDiff())
"ForwardDiff"
```

### CODE REVIEW

File: DifferentiationInterface/src/utils/printing.jl [hunk 1]
```diff
@@ -1,8 +1,10 @@
 function package_name(b::AbstractADType)
     s = string(b)
+    s = chopprefix(s, "ADTypes.")
+    s = chopprefix(s, "Auto")
```
Comment (avik-pal) [inline DifferentiationInterface/src/utils/printing.jl:4]: a simpler version would be `nameof(typeof(b))[5:(k - 1)]`

Comment (gdalle) [reply DifferentiationInterface/src/utils/printing.jl:4]: good point, if I ever run into another similar issue I'll remember it
