### PR TITLE
Fix Enzyme's batched pullback and Jacobian

### LINKED ISSUE #312: Vector / chunked / batch mode
This one is rather easy in principle: just wrap the JVP/VJP/HVP seed in a Batch struct that is essentially a named tuple, and dispatch on that

### PR DESCRIPTION
**Pull request by gdalle**
**DI extensions**

- Enzyme: make batched pullback work for number input `x` by setting the mode width manually (see https://github.com/EnzymeAD/Enzyme.jl/issues/1883#issuecomment-2371461934)
- Enzyme: adapt to Jacobian fix in https://github.com/EnzymeAD/Enzyme.jl/pull/1864

### CODE REVIEW

File: DifferentiationInterface/ext/DifferentiationInterfaceEnzymeExt/utils.jl [hunk 1]
```diff
@@ -115,6 +115,32 @@ function mode_split(
     }()
 end
 
+function set_width(
```
Comment (wsmoses) [inline DifferentiationInterface/ext/DifferentiationInterfaceEnzymeExt/utils.jl:118]: can you add this to enzymecore proper?

Comment (gdalle) [reply DifferentiationInterface/ext/DifferentiationInterfaceEnzymeExt/utils.jl:118]: yeah I will, opened https://github.com/EnzymeAD/Enzyme.jl/issues/1897 to keep track
